// <auto-generated />
using System;
using ClassificadosApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassificadosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926152726_ImproveClassificadoModel")]
    partial class ImproveClassificadoModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassificadosApi.Models.Classificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Classificados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2024, 4, 23, 20, 38, 30, 0, DateTimeKind.Utc),
                            Descricao = "Descricao teste teste teste",
                            Titulo = "Teste 1"
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2024, 4, 23, 20, 40, 0, 0, DateTimeKind.Utc),
                            Descricao = "Teste de descricao",
                            Titulo = "Teste 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
